"use client";
import {useMemo,useState} from "react";
const products=[["CORE TEE","TEES",68,"light"],["DISTRICT HOODIE","HOODIES",128,"dark"],["AFTER DARK CAP","ACCESSORIES",48,"stone"],["STREET FORM PANT","BOTTOMS",118,"warm"],["ZIP JACKET","JACKETS",178,"olive"],["SIGNAL LS","TEES",88,"ink"]];
export default function Storefront(){const [bag,setBag]=useState(0),[filter,setFilter]=useState("ALL"),[search,setSearch]=useState(false);const shown=useMemo(()=>filter==="ALL"?products:products.filter(x=>x[1]===filter),[filter]);return <main>
<div className="announcement">FREE SHIPPING ON ORDERS OVER $150 <span>·</span> NEW DROP / LIMITED RUNS</div>
<header className="site-header"><a className="logo" href="#">RUNAWAY<span>®</span></a><nav><a href="#shop">SHOP</a><a href="#collections">COLLECTIONS</a><a href="#story">ABOUT</a><a href="#journal">JOURNAL</a></nav><div className="actions"><button onClick={()=>setSearch(!search)}>SEARCH</button><button>ACCOUNT</button><button onClick={()=>document.getElementById("bag")?.classList.add("show")}>BAG ({bag})</button></div></header>
{search&&<div className="search-panel"><input autoFocus placeholder="SEARCH RUNAWAY"/><button onClick={()=>setSearch(false)}>ESC</button></div>}
<section className="hero"><div className="hero-copy"><p className="eyebrow">RUNAWAY / DROP 01 / 2026</p><h1>MOVE<br/><i>WITHOUT</i><br/>PERMISSION.</h1><p className="lede">Independent clothing for the restless. Cut clean. Built hard. Made to move with you.</p><a className="cta" href="#shop">SHOP THE DROP <span>↗</span></a><div className="hero-meta"><span>01 — 06</span><span>SCROLL TO EXPLORE ↓</span></div></div><div className="hero-visual"><div className="visual-noise"/><div className="visual-ring ring-one"/><div className="visual-ring ring-two"/><div className="visual-type">RW<br/>001</div><div className="visual-word">RUN<br/><i>AWAY</i></div><div className="visual-caption">THE FIRST COLLECTION<br/>FOR THOSE GOING THEIR OWN WAY.</div></div></section>
<div className="ticker"><div>RUNAWAY — MOVE DIFFERENT — RUNAWAY — NO FIXED ADDRESS — RUNAWAY — MOVE DIFFERENT —</div></div>
<section id="shop" className="shop"><div className="section-head"><div><p className="eyebrow">01 / SHOP</p><h2>THE<br/><i>DROP.</i></h2></div><p className="section-intro">A focused edit of everyday pieces. Limited quantities, considered details and a uniform for wherever you end up.</p><a className="view-all" href="#shop">VIEW ALL ↗</a></div><div className="filters">{["ALL","TEES","HOODIES","JACKETS","BOTTOMS","ACCESSORIES"].map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="grid">{shown.map((x,i)=><article className="product" key={x[0]}><button className="product-image" onClick={()=>setBag(n=>n+1)}><div className={"product-art "+x[3]}><span>{String(i+1).padStart(2,"0")}</span><b>RW</b><small>LIMITED</small></div><div className="quick-add">ADD TO BAG +</div></button><div className="product-meta"><div><h3>RUNAWAY {x[0]}</h3><p>{x[1]} / ESSENTIALS</p></div><strong>{"$"}{x[2]}</strong></div></article>)}</div></section>
<section id="collections" className="manifesto"><div className="manifesto-top"><span>02 / MANIFESTO</span><span>EST. 2026 / EVERYWHERE</span></div><p>NO MAPS.<br/>NO RULES.<br/><i>JUST FORWARD.</i></p><a className="circle-link" href="#shop">EXPLORE<br/>THE COLLECTION<br/>↗</a></section>
<section id="story" className="story"><div><p className="eyebrow">03 / ABOUT RUNAWAY</p><h2>MADE FOR THE<br/><i>RESTLESS.</i></h2></div><div className="story-copy"><p>RUNAWAY started with one idea: your clothes should never tell you where you belong.</p><p>We make understated pieces with an unmistakable point of view. Designed in small runs. Released when they are ready. Worn wherever the road takes you.</p><a href="#journal">READ OUR STORY ↗</a></div></section>
<section id="journal" className="journal"><div className="section-head"><div><p className="eyebrow">04 / JOURNAL</p><h2>KEEP<br/><i>MOVING.</i></h2></div><p className="section-intro">Notes on movement, cities, music, design and the people who refuse to stand still.</p></div><div className="journal-grid">{["THE CITY AFTER MIDNIGHT","WHY WE DON'T DO RESTOCKS","THE RUNAWAY UNIFORM"].map((x,i)=><article key={x}><div className={"journal-art j"+(i+1)}>{String(i+1).padStart(2,"0")}</div><p>FIELD NOTES / 00{i+1}</p><h3>{x}</h3></article>)}</div></section>
<footer><div className="footer-main"><div className="logo">RUNAWAY<span>®</span></div><div><p>STAY IN MOTION.</p><form onSubmit={e=>e.preventDefault()}><input placeholder="EMAIL ADDRESS"/><button>JOIN ↗</button></form></div></div><div className="footer-bottom"><span>© 2026 RUNAWAY</span><div><a href="#">INSTAGRAM</a><a href="#">CONTACT</a><a href="#">SHIPPING</a></div><span>ALL RIGHTS RESERVED.</span></div></footer>
<div id="bag" className="bag-drawer"><button onClick={()=>document.getElementById("bag")?.classList.remove("show")}>CLOSE ×</button><p className="eyebrow">YOUR BAG</p><h2>{bag?bag+" ITEM"+(bag>1?"S":""):"EMPTY."}</h2><p>{bag?"Your selected pieces are ready to move.":"Nothing here yet."}</p><a className="cta" href="#shop">CONTINUE SHOPPING</a></div></main>}